### ISSUE TITLE
The tutorial use outdated JS SDK.

### ISSUE THREAD

**Issue by changbenny** [ringcentral/ringcentral.github.io#20]
In the code example of Javascript tutorial, some methods is renamed in new versioned JS SDK.
I would like to send a PR to fix it, but I am not familiar with the Slate's documentation generation process, could you provide me some instructions?

**Comment by grokify** [comment]
There was a major version upgrade of the JS SDK from 1.x to 2.x so a number of things have changed and need to be incorporated.

To read up on Slate, please see the project repo at: https://github.com/tripit/slate

Also, since this is the GitHub pages repo, please use the `slate` branch of the `ringcentral/slate` repo for your updates and PRs:

https://github.com/ringcentral/slate/tree/ringcentral

**Comment by changbenny** [comment]
Got it, thanks for the suggestion.
